import { createContext, useContext, useState, ReactNode } from 'react';

type Language = 'zh' | 'en' | 'fr' | 'ar' | 'es';

interface LanguageContextType {
  language: Language;
  setLanguage: (lang: Language) => void;
  t: (key: string) => string;
}

const LanguageContext = createContext<LanguageContextType | undefined>(undefined);

export const useLanguage = () => {
  const context = useContext(LanguageContext);
  if (!context) {
    throw new Error('useLanguage must be used within a LanguageProvider');
  }
  return context;
};

interface LanguageProviderProps {
  children: ReactNode;
}

export const LanguageProvider = ({ children }: LanguageProviderProps) => {
  const [language, setLanguage] = useState<Language>('zh');

  const t = (key: string): string => {
    const translations = getTranslations(language);
    const keys = key.split('.');
    let value: any = translations;

    for (const k of keys) {
      value = value?.[k];
    }

    return value || key;
  };

  return (
    <LanguageContext.Provider value={{ language, setLanguage, t }}>
      {children}
    </LanguageContext.Provider>
  );
};

const getTranslations = (lang: Language) => {
  const translations = {
    zh: zhTranslations,
    en: enTranslations,
    fr: frTranslations,
    ar: arTranslations,
    es: esTranslations,
  };
  return translations[lang];
};

const zhTranslations = {
  nav: {
    home: '首页',
    projects: '项目',
    cases: '案例',
    faq: 'FAQ',
    login: '登录',
    logout: '退出登录',
    bookNow: '立即预约',
    facialContour: '面部轮廓',
    bodySculpting: '身体塑形',
    facialRejuvenation: '面部年轻化',
    hairTransplant: '植发',
    dental: '牙齿美容',
  },
  hero: {
    title1: '只有自然独一无二的，',
    title2: '你才是这个世界上最独特的符号',
    cta: '现在开始探索',
  },
  services: {
    beforePlaceholder: '【此处放置案例照片 A】',
    afterPlaceholder: '【此处放置案例照片 B】',
  },
  advantages: {
    title: '我们的优势',
    advantage1: '注重面部整体比例和谐',
    advantage2: '专业的面诊评估',
    advantage3: '专注于整体特征',
    advantage4: '看看未来的自己',
    advantage5: '基于美学的个性化方案',
  },
  ethnicity: {
    title: '不同人种的面部特征',
    subtitle: '注重面部整体比例和谐，基于美学对不同人种有个性化的定制方案',
    black: '黑人',
    asian: '黄种人',
    white: '白人',
    boneFeatures: '骨骼特征：',
    softTissue: '软组织特征：',
    blackBone: '面中部常显前突，但鼻骨低平；眶距可能较宽；下颌骨发达，嘴唇极厚且唇红外翻。',
    blackSoft: '皮肤较厚，不易长皱纹但需关注瘢痕愈合；鼻翼宽大，鼻孔扁平，鼻小柱短；多为双眼皮但形态深邃。',
    asianBone: '颧骨常显外扩，下颌角棱角分明，眉骨与眶缘发育平缓。',
    asianSoft: '单眼皮或内双比例高，常伴有内眦赘皮；鼻梁偏低，鼻头圆润，鼻基底凹陷；软组织相对丰厚。',
    whiteBone: '眉骨与眶缘极为突出，颧骨转向侧面，下颌骨线条分明，下巴尖翘。',
    whiteSoft: '皮肤较薄，脂肪含量少，容易出现皱纹和骨相显露；鼻梁高挺，鼻翼窄，嘴唇偏薄；双眼皮宽而深。',
    cta: '了解你的面部特征，立即开始行之有效的行动来提升你的容颜',
  },
  plan: {
    title: '获取你的手术计划',
    subtitle: '了解你的面部特征，立即开始行之有效的行动来提升你的容颜',
    before: '术前照片 (Before)',
    after: '术后照片 (After)',
    beforeLabel: 'BEFORE',
    afterLabel: 'AFTER',
    step1: '获取专家面部分析',
    step2: '你最美的样子',
    step3: '获取你的专属焕颜方案',
    step4: '见证显著效果',
  },
  analysis: {
    title: '你的脸，独一无二的解法',
    subtitle: '基于人种骨架、动态肌肉与心理诉求的六维面诊分析法',
    dimension1: '轮廓与骨相维度',
    dimension2: '软组织与皮相维度',
    dimension3: '五官局部维度',
    dimension4: '动态与肌肉维度',
  },
  vision: {
    title: '有没有想过你的脸会是什么样子',
    subtitle: '展望未来',
  },
  realCases: {
    title: '真实案例对比',
    before: '手术前',
    after: '手术后',
    months: '个月',
    case1Title1: '面部轮廓立体提升',
    case1Desc1: '通过专业的面部轮廓手术，使面部线条更加立体分明',
    case1Title2: '鼻梁挺拔自然',
    case1Desc2: '精准的鼻部整形技术，打造自然挺拔的鼻梁线条',
    case1Title3: '下颌线条优化',
    case1Desc3: '塑造流畅优雅的下颌线条，提升整体面部和谐度',
    case2Title1: '眼部轮廓精致化',
    case2Desc1: '打造深邃迷人的双眼，让眼神更加有神采',
    case2Title2: '皮肤紧致提升',
    case2Desc2: '改善肌肤松弛问题，恢复年轻紧致状态',
    case2Title3: '整体气质提升',
    case2Desc3: '细节调整，打造更加协调自然的面部美感',
  },
  caseStudies: {
    title: '成功案例',
    viewAll: '查看所有案例',
  },
  testimonials: {
    title: '客户对我们的评价',
    mapTitle: '我们的客户遍布全世界',
    mapSubtitle: '让客户满意是我们的永恒的追求',
    readMore: '快来看看',
  },
  journey: {
    title: '今天开始你的蜕变之旅',
    step1: '点击回答问题',
    step2: '上传图片',
    step3: '为你定制专属方案',
    step4: '为你开启旅途',
    cta: '开启你的蜕变之旅',
  },
  footer: {
    tagline: '专业医美整形，成就更美的你',
    about: '关于我们',
    contact: '联系方式',
    privacy: '隐私政策',
    terms: '服务条款',
  },
  facialContour: {
    title: '面部轮廓',
    subtitle: '精准塑造，打造立体五官',
    exploreNow: '现在开始探索',
    servicesTitle: '服务项目',
    servicesSubtitle: '专业技术，量身定制',
    whyChooseUs: '为什么选择我们',
    realCasesTitle: '真实案例',
    realCasesSubtitle: '见证专业技术带来的美丽蜕变',
  },
  bodySculpting: {
    title: '身体塑形',
    subtitle: '科学塑形，雕刻完美曲线',
    exploreNow: '现在开始探索',
    servicesTitle: '服务项目',
    servicesSubtitle: '专业塑形，重塑自信',
    whyChooseUs: '为什么选择我们',
    realCasesTitle: '真实案例',
    realCasesSubtitle: '见证专业技术带来的完美蜕变',
  },
  facialRejuvenation: {
    title: '面部年轻化',
    subtitle: '非手术方式，轻松实现年轻化效果',
    exploreNow: '现在开始探索',
    servicesTitle: '服务项目',
    servicesSubtitle: '无创年轻化，重塑自然美感',
    injection: '注射提升',
    injectionDesc: '抚平动态皱纹',
    diamond: '7D钻石提升',
    diamondDesc: '恢复面部饱满',
    whyChooseUs: '为什么选择我们',
    realCasesTitle: '真实案例',
    realCasesSubtitle: '见证专业技术带来的美丽蜕变',
  },
  hairTransplant: {
    title: '植发',
    subtitle: '专业植发技术，重拾浓密秀发',
    exploreNow: '现在开始探索',
    servicesTitle: '植发技术',
    servicesSubtitle: '先进技术，自然效果',
    whyChooseUs: '为什么选择我们',
    realCasesTitle: '真实案例',
    realCasesSubtitle: '见证专业技术带来的秀发重生',
  },
  dental: {
    title: '牙齿美容',
    subtitle: '专业口腔美学，绽放自信笑容',
    exploreNow: '现在开始探索',
    servicesTitle: '服务项目',
    servicesSubtitle: '精湛技术，完美笑容',
    whyChooseUs: '为什么选择我们',
    realCasesTitle: '真实案例',
    realCasesSubtitle: '见证专业技术带来的灿烂笑容',
  },
  cases: {
    title: '成功案例',
    subtitle: '真实蜕变，见证美丽',
    filterAll: '全部',
    searchPlaceholder: '搜索案例...',
    loadMore: '加载更多',
    noResults: '暂无案例',
  },
  faq: {
    title: '常见问题',
    subtitle: '为您解答疑惑',
    general: '常规问题',
    safety: '安全相关',
    recovery: '恢复相关',
    cost: '费用相关',
    q1: '整形手术安全吗？',
    a1: '我们采用国际先进的设备和材料，由经验丰富的医师团队操作，确保手术的安全性。',
    q2: '恢复期需要多长时间？',
    a2: '恢复时间因手术类型而异。微创手术如注射类项目几乎无恢复期，手术类项目通常需要1-2周。',
    q3: '手术效果能维持多久？',
    a3: '注射类项目通常可维持6-12个月，手术类项目效果可以长期保持。',
    q4: '费用如何计算？',
    a4: '费用根据具体项目和个人情况而定。我们会在面诊后提供透明的报价方案。',
    contactUs: '还有其他问题？',
    contactCTA: '联系我们获取更多信息',
  },
  booking: {
    title: '立即预约',
    subtitle: '填写您的信息，我们的专业团队将尽快与您联系',
    firstName: '名',
    lastName: '姓',
    email: '邮箱',
    phone: '电话',
    required: '*',
    firstNamePlaceholder: '名',
    lastNamePlaceholder: '姓',
    emailPlaceholder: '请输入您的邮箱地址',
    phonePlaceholder: '请输入您的电话号码',
    submit: '提交预约',
    submitting: '提交中...',
    vipTitle: '终身VIP会员',
    vipPrice: '$200',
    vipDescription: '享受终身尊享服务与专属优惠',
    selectServices: '选择服务项目',
    injection: '注射改善',
    injectionDesc: '微创注射美容方案',
    injectionPrice: '$40',
    surgery: '通过手术改善',
    surgeryDesc: '专业手术美容方案',
    surgeryPrice: '$80',
    hairConsult: '头发建议',
    hairConsultDesc: '专业毛发健康咨询',
    hairConsultPrice: '$20',
    paypalPayment: 'PayPal支付',
    cardPayment: '银行卡支付',
    processing: '处理中...',
    backToHome: '返回首页',
    successTitle: '预约成功！',
    successMessage: '您的预约已确认，我们的团队将尽快与您联系',
  },
};

const enTranslations = {
  nav: {
    home: 'Home',
    projects: 'Projects',
    cases: 'Cases',
    faq: 'FAQ',
    login: 'Login',
    logout: 'Logout',
    bookNow: 'Book Now',
    facialContour: 'Facial Contouring',
    bodySculpting: 'Body Sculpting',
    facialRejuvenation: 'Facial Rejuvenation',
    hairTransplant: 'Hair Transplant',
    dental: 'Dental Aesthetics',
  },
  hero: {
    title1: 'Only what is naturally unique,',
    title2: 'Makes you the most distinctive symbol in the world',
    cta: 'Start Exploring Now',
  },
  services: {
    beforePlaceholder: '[Before Photo]',
    afterPlaceholder: '[After Photo]',
  },
  advantages: {
    title: 'Our Advantages',
    advantage1: 'Focus on Overall Facial Harmony',
    advantage2: 'Professional Consultation',
    advantage3: 'Holistic Features Approach',
    advantage4: 'Visualize Your Future Self',
    advantage5: 'Personalized Aesthetic Plans',
  },
  ethnicity: {
    title: 'Facial Features by Ethnicity',
    subtitle: 'Emphasizing overall facial harmony with personalized solutions based on aesthetic principles for different ethnicities',
    black: 'African',
    asian: 'Asian',
    white: 'Caucasian',
    boneFeatures: 'Bone Structure:',
    softTissue: 'Soft Tissue:',
    blackBone: 'Midface protrusion with low nasal bridge; possibly wider orbital distance; developed mandible with thick, everted lips.',
    blackSoft: 'Thicker skin, wrinkle-resistant but requires attention to scar healing; wide nostrils, flat nose, short columella; often double eyelids with deep-set appearance.',
    asianBone: 'Prominent cheekbones, angular mandible, gentle brow bone and orbital rim development.',
    asianSoft: 'High proportion of monolids or inner double eyelids with epicanthal folds; lower nasal bridge, rounded tip, recessed nasal base; relatively fuller soft tissue.',
    whiteBone: 'Prominent brow bone and orbital rim, lateral cheekbones, defined jawline, pointed chin.',
    whiteSoft: 'Thinner skin with less fat, prone to wrinkles and bone prominence; high nasal bridge, narrow nostrils, thinner lips; wide, deep double eyelids.',
    cta: 'Understand your facial features and start effective actions to enhance your appearance',
  },
  plan: {
    title: 'Get Your Treatment Plan',
    subtitle: 'Understand your facial features and start effective actions to enhance your appearance',
    before: 'Before Photo',
    after: 'After Photo',
    beforeLabel: 'BEFORE',
    afterLabel: 'AFTER',
    step1: 'Expert Facial Analysis',
    step2: 'Your Best Self',
    step3: 'Personalized Enhancement Plan',
    step4: 'Witness Remarkable Results',
  },
  analysis: {
    title: 'Your Face, Your Unique Solution',
    subtitle: 'Six-dimensional facial analysis based on ethnic bone structure, dynamic muscles, and psychological needs',
    dimension1: '1. Contour & Bone Structure',
    dimension2: '2. Soft Tissue & Skin',
    dimension3: '3. Individual Features',
    dimension4: '4. Dynamic & Muscles',
  },
  vision: {
    title: 'Ever Wondered What Your Face Could Look Like',
    subtitle: 'Envision Your Future',
  },
  realCases: {
    title: 'Real Case Comparisons',
    before: 'Before',
    after: 'After',
    months: 'months',
    case1Title1: 'Enhanced Facial Contours',
    case1Desc1: 'Professional facial contouring surgery creates more defined facial lines',
    case1Title2: 'Natural Nasal Bridge',
    case1Desc2: 'Precise rhinoplasty techniques create naturally elevated nasal lines',
    case1Title3: 'Optimized Jawline',
    case1Desc3: 'Sculpting smooth, elegant jawline enhances overall facial harmony',
    case2Title1: 'Refined Eye Contours',
    case2Desc1: 'Creating deep, captivating eyes with more expressive gaze',
    case2Title2: 'Skin Tightening',
    case2Desc2: 'Improving skin laxity, restoring youthful firmness',
    case2Title3: 'Overall Enhancement',
    case2Desc3: 'Detail adjustments creating more harmonious natural facial beauty',
  },
  caseStudies: {
    title: 'Success Stories',
    viewAll: 'View All Cases',
  },
  testimonials: {
    title: 'What Our Clients Say',
    mapTitle: 'Our Clients Around the World',
    mapSubtitle: 'Client satisfaction is our eternal pursuit',
    readMore: 'Read More',
  },
  journey: {
    title: 'Start Your Transformation Journey Today',
    step1: 'Answer Questions',
    step2: 'Upload Photos',
    step3: 'Get Personalized Plan',
    step4: 'Begin Your Journey',
    cta: 'Start Your Transformation',
  },
  footer: {
    tagline: 'Professional Medical Aesthetics, Achieving a Better You',
    about: 'About Us',
    contact: 'Contact',
    privacy: 'Privacy Policy',
    terms: 'Terms of Service',
  },
  facialContour: {
    title: 'Facial Contouring',
    subtitle: 'Precision Sculpting, Creating Defined Features',
    exploreNow: 'Start Exploring Now',
    servicesTitle: 'Our Services',
    servicesSubtitle: 'Professional Techniques, Tailored Solutions',
    whyChooseUs: 'Why Choose Us',
    realCasesTitle: 'Real Cases',
    realCasesSubtitle: 'Witness Beautiful Transformations',
  },
  bodySculpting: {
    title: 'Body Sculpting',
    subtitle: 'Scientific Contouring, Perfect Curves',
    exploreNow: 'Start Exploring Now',
    servicesTitle: 'Our Services',
    servicesSubtitle: 'Professional Sculpting, Renewed Confidence',
    whyChooseUs: 'Why Choose Us',
    realCasesTitle: 'Real Cases',
    realCasesSubtitle: 'Witness Perfect Transformations',
  },
  facialRejuvenation: {
    title: 'Facial Rejuvenation',
    subtitle: 'Non-Surgical Approach, Easy Rejuvenation',
    exploreNow: 'Start Exploring Now',
    servicesTitle: 'Our Services',
    servicesSubtitle: 'Non-Invasive Rejuvenation, Natural Beauty',
    injection: 'Injectable Lifting',
    injectionDesc: 'Smooth Dynamic Wrinkles',
    diamond: '7D Diamond Lifting',
    diamondDesc: 'Restore Facial Fullness',
    whyChooseUs: 'Why Choose Us',
    realCasesTitle: 'Real Cases',
    realCasesSubtitle: 'Witness Beautiful Transformations',
  },
  hairTransplant: {
    title: 'Hair Transplant',
    subtitle: 'Professional Technology, Regain Thick Hair',
    exploreNow: 'Start Exploring Now',
    servicesTitle: 'Hair Transplant Techniques',
    servicesSubtitle: 'Advanced Technology, Natural Results',
    whyChooseUs: 'Why Choose Us',
    realCasesTitle: 'Real Cases',
    realCasesSubtitle: 'Witness Hair Rebirth',
  },
  dental: {
    title: 'Dental Aesthetics',
    subtitle: 'Professional Oral Aesthetics, Confident Smile',
    exploreNow: 'Start Exploring Now',
    servicesTitle: 'Our Services',
    servicesSubtitle: 'Exquisite Techniques, Perfect Smile',
    whyChooseUs: 'Why Choose Us',
    realCasesTitle: 'Real Cases',
    realCasesSubtitle: 'Witness Brilliant Smiles',
  },
  cases: {
    title: 'Success Stories',
    subtitle: 'Real Transformations, Witnessing Beauty',
    filterAll: 'All',
    searchPlaceholder: 'Search cases...',
    loadMore: 'Load More',
    noResults: 'No cases found',
  },
  faq: {
    title: 'Frequently Asked Questions',
    subtitle: 'Answering Your Questions',
    general: 'General Questions',
    safety: 'Safety Related',
    recovery: 'Recovery Related',
    cost: 'Cost Related',
    q1: 'Is cosmetic surgery safe?',
    a1: 'We use internationally advanced equipment and materials, operated by experienced medical teams, ensuring surgical safety.',
    q2: 'How long is the recovery period?',
    a2: 'Recovery time varies by surgery type. Minimally invasive procedures have almost no downtime, surgical procedures typically require 1-2 weeks.',
    q3: 'How long do results last?',
    a3: 'Injectable treatments typically last 6-12 months, surgical procedures can have long-term effects.',
    q4: 'How are costs calculated?',
    a4: 'Costs depend on specific procedures and individual circumstances. We provide transparent pricing after consultation.',
    contactUs: 'Have other questions?',
    contactCTA: 'Contact us for more information',
  },
  booking: {
    title: 'Book Now',
    subtitle: 'Fill in your information and our professional team will contact you soon',
    firstName: 'First Name',
    lastName: 'Last Name',
    email: 'Email',
    phone: 'Phone',
    required: '*',
    firstNamePlaceholder: 'First Name',
    lastNamePlaceholder: 'Last Name',
    emailPlaceholder: 'Enter your email address',
    phonePlaceholder: 'Enter your phone number',
    submit: 'Submit Booking',
    submitting: 'Submitting...',
    vipTitle: 'Lifetime VIP Membership',
    vipPrice: '$200',
    vipDescription: 'Enjoy lifetime exclusive services and special offers',
    selectServices: 'Select Services',
    injection: 'Injection Enhancement',
    injectionDesc: 'Minimally invasive injection solutions',
    injectionPrice: '$40',
    surgery: 'Surgical Enhancement',
    surgeryDesc: 'Professional surgical solutions',
    surgeryPrice: '$80',
    hairConsult: 'Hair Consultation',
    hairConsultDesc: 'Professional hair health consultation',
    hairConsultPrice: '$20',
    paypalPayment: 'Pay with PayPal',
    cardPayment: 'Pay with Card',
    processing: 'Processing...',
    backToHome: 'Back to Home',
    successTitle: 'Booking Successful!',
    successMessage: 'Your booking is confirmed, our team will contact you soon',
  },
};

const frTranslations = {
  nav: {
    home: 'Accueil',
    projects: 'Projets',
    cases: 'Cas',
    faq: 'FAQ',
    login: 'Connexion',
    logout: 'Déconnexion',
    bookNow: 'Réserver',
    facialContour: 'Contour Facial',
    bodySculpting: 'Sculpture Corporelle',
    facialRejuvenation: 'Rajeunissement Facial',
    hairTransplant: 'Greffe de Cheveux',
    dental: 'Esthétique Dentaire',
  },
  hero: {
    title1: 'Seul ce qui est naturellement unique,',
    title2: 'Fait de vous le symbole le plus distinctif au monde',
    cta: 'Commencer à Explorer',
  },
  services: {
    beforePlaceholder: '[Photo Avant]',
    afterPlaceholder: '[Photo Après]',
  },
  advantages: {
    title: 'Nos Avantages',
    advantage1: 'Focus sur l\'Harmonie Faciale Globale',
    advantage2: 'Consultation Professionnelle',
    advantage3: 'Approche Holistique',
    advantage4: 'Visualisez Votre Futur Moi',
    advantage5: 'Plans Esthétiques Personnalisés',
  },
  ethnicity: {
    title: 'Caractéristiques Faciales par Ethnicité',
    subtitle: 'Mettant l\'accent sur l\'harmonie faciale globale avec des solutions personnalisées basées sur les principes esthétiques pour différentes ethnicités',
    black: 'Africain',
    asian: 'Asiatique',
    white: 'Caucasien',
    boneFeatures: 'Structure Osseuse:',
    softTissue: 'Tissus Mous:',
    blackBone: 'Protrusion du milieu du visage avec un pont nasal bas; distance orbitale possiblement plus large; mandibule développée avec des lèvres épaisses et éversées.',
    blackSoft: 'Peau plus épaisse, résistante aux rides mais nécessitant une attention à la cicatrisation; narines larges, nez plat, columelle courte; souvent paupières doubles avec apparence profonde.',
    asianBone: 'Pommettes proéminentes, mandibule angulaire, développement doux de l\'arcade sourcilière et du rebord orbital.',
    asianSoft: 'Haute proportion de paupières simples ou doubles internes avec plis épicanthiques; pont nasal plus bas, pointe arrondie, base nasale en retrait; tissu mou relativement plus plein.',
    whiteBone: 'Arcade sourcilière et rebord orbital proéminents, pommettes latérales, ligne de mâchoire définie, menton pointu.',
    whiteSoft: 'Peau plus fine avec moins de graisse, sujette aux rides et à la proéminence osseuse; pont nasal élevé, narines étroites, lèvres plus fines; paupières doubles larges et profondes.',
    cta: 'Comprenez vos caractéristiques faciales et commencez des actions efficaces pour améliorer votre apparence',
  },
  plan: {
    title: 'Obtenez Votre Plan de Traitement',
    subtitle: 'Comprenez vos caractéristiques faciales et commencez des actions efficaces pour améliorer votre apparence',
    before: 'Photo Avant',
    after: 'Photo Après',
    beforeLabel: 'AVANT',
    afterLabel: 'APRÈS',
    step1: 'Analyse Faciale Experte',
    step2: 'Votre Meilleur Vous',
    step3: 'Plan d\'Amélioration Personnalisé',
    step4: 'Témoignez de Résultats Remarquables',
  },
  analysis: {
    title: 'Votre Visage, Votre Solution Unique',
    subtitle: 'Analyse faciale en six dimensions basée sur la structure osseuse ethnique, les muscles dynamiques et les besoins psychologiques',
    dimension1: '1. Contour et Structure Osseuse',
    dimension2: '2. Tissus Mous et Peau',
    dimension3: '3. Caractéristiques Individuelles',
    dimension4: '4. Dynamique et Muscles',
  },
  vision: {
    title: 'Vous Êtes-vous Déjà Demandé À Quoi Votre Visage Pourrait Ressembler',
    subtitle: 'Envisagez Votre Avenir',
  },
  realCases: {
    title: 'Comparaisons de Cas Réels',
    before: 'Avant',
    after: 'Après',
    months: 'mois',
    case1Title1: 'Contours Faciaux Améliorés',
    case1Desc1: 'La chirurgie professionnelle de contour facial crée des lignes faciales plus définies',
    case1Title2: 'Pont Nasal Naturel',
    case1Desc2: 'Des techniques de rhinoplastie précises créent des lignes nasales naturellement élevées',
    case1Title3: 'Ligne de Mâchoire Optimisée',
    case1Desc3: 'Sculpter une ligne de mâchoire lisse et élégante améliore l\'harmonie faciale globale',
    case2Title1: 'Contours des Yeux Raffinés',
    case2Desc1: 'Créer des yeux profonds et captivants avec un regard plus expressif',
    case2Title2: 'Raffermissement de la Peau',
    case2Desc2: 'Améliorer le relâchement cutané, restaurer la fermeté juvénile',
    case2Title3: 'Amélioration Globale',
    case2Desc3: 'Ajustements détaillés créant une beauté faciale naturelle plus harmonieuse',
  },
  caseStudies: {
    title: 'Histoires de Succès',
    viewAll: 'Voir Tous les Cas',
  },
  testimonials: {
    title: 'Ce Que Disent Nos Clients',
    mapTitle: 'Nos Clients Dans le Monde',
    mapSubtitle: 'La satisfaction du client est notre quête éternelle',
    readMore: 'Lire Plus',
  },
  journey: {
    title: 'Commencez Votre Voyage de Transformation Aujourd\'hui',
    step1: 'Répondre aux Questions',
    step2: 'Télécharger des Photos',
    step3: 'Obtenir un Plan Personnalisé',
    step4: 'Commencer Votre Voyage',
    cta: 'Commencer Votre Transformation',
  },
  footer: {
    tagline: 'Esthétique Médicale Professionnelle, Pour un Meilleur Vous',
    about: 'À Propos',
    contact: 'Contact',
    privacy: 'Politique de Confidentialité',
    terms: 'Conditions d\'Utilisation',
  },
  facialContour: {
    title: 'Contour Facial',
    subtitle: 'Sculpture Précise, Créer des Traits Définis',
    exploreNow: 'Commencer à Explorer',
    servicesTitle: 'Nos Services',
    servicesSubtitle: 'Techniques Professionnelles, Solutions Sur Mesure',
    whyChooseUs: 'Pourquoi Nous Choisir',
    realCasesTitle: 'Cas Réels',
    realCasesSubtitle: 'Témoignez de Belles Transformations',
  },
  bodySculpting: {
    title: 'Sculpture Corporelle',
    subtitle: 'Contournage Scientifique, Courbes Parfaites',
    exploreNow: 'Commencer à Explorer',
    servicesTitle: 'Nos Services',
    servicesSubtitle: 'Sculpture Professionnelle, Confiance Renouvelée',
    whyChooseUs: 'Pourquoi Nous Choisir',
    realCasesTitle: 'Cas Réels',
    realCasesSubtitle: 'Témoignez de Transformations Parfaites',
  },
  facialRejuvenation: {
    title: 'Rajeunissement Facial',
    subtitle: 'Approche Non Chirurgicale, Rajeunissement Facile',
    exploreNow: 'Commencer à Explorer',
    servicesTitle: 'Nos Services',
    servicesSubtitle: 'Rajeunissement Non Invasif, Beauté Naturelle',
    injection: 'Lifting par Injection',
    injectionDesc: 'Lisser les Rides Dynamiques',
    diamond: 'Lifting Diamant 7D',
    diamondDesc: 'Restaurer la Plénitude Faciale',
    whyChooseUs: 'Pourquoi Nous Choisir',
    realCasesTitle: 'Cas Réels',
    realCasesSubtitle: 'Témoignez de Belles Transformations',
  },
  hairTransplant: {
    title: 'Greffe de Cheveux',
    subtitle: 'Technologie Professionnelle, Retrouver des Cheveux Épais',
    exploreNow: 'Commencer à Explorer',
    servicesTitle: 'Techniques de Greffe',
    servicesSubtitle: 'Technologie Avancée, Résultats Naturels',
    whyChooseUs: 'Pourquoi Nous Choisir',
    realCasesTitle: 'Cas Réels',
    realCasesSubtitle: 'Témoignez de la Renaissance Capillaire',
  },
  dental: {
    title: 'Esthétique Dentaire',
    subtitle: 'Esthétique Orale Professionnelle, Sourire Confiant',
    exploreNow: 'Commencer à Explorer',
    servicesTitle: 'Nos Services',
    servicesSubtitle: 'Techniques Exquises, Sourire Parfait',
    whyChooseUs: 'Pourquoi Nous Choisir',
    realCasesTitle: 'Cas Réels',
    realCasesSubtitle: 'Témoignez de Sourires Brillants',
  },
  cases: {
    title: 'Histoires de Succès',
    subtitle: 'Transformations Réelles, Témoigner de la Beauté',
    filterAll: 'Tous',
    searchPlaceholder: 'Rechercher des cas...',
    loadMore: 'Charger Plus',
    noResults: 'Aucun cas trouvé',
  },
  faq: {
    title: 'Questions Fréquemment Posées',
    subtitle: 'Répondre à Vos Questions',
    general: 'Questions Générales',
    safety: 'Lié à la Sécurité',
    recovery: 'Lié à la Récupération',
    cost: 'Lié aux Coûts',
    q1: 'La chirurgie esthétique est-elle sûre?',
    a1: 'Nous utilisons des équipements et matériaux de pointe, opérés par des équipes médicales expérimentées, garantissant la sécurité chirurgicale.',
    q2: 'Combien de temps dure la période de récupération?',
    a2: 'Le temps de récupération varie selon le type de chirurgie. Les procédures mini-invasives n\'ont presque pas de temps d\'arrêt, les procédures chirurgicales nécessitent généralement 1-2 semaines.',
    q3: 'Combien de temps durent les résultats?',
    a3: 'Les traitements injectables durent généralement 6-12 mois, les procédures chirurgicales peuvent avoir des effets à long terme.',
    q4: 'Comment les coûts sont-ils calculés?',
    a4: 'Les coûts dépendent des procédures spécifiques et des circonstances individuelles. Nous fournissons des prix transparents après consultation.',
    contactUs: 'Avez-vous d\'autres questions?',
    contactCTA: 'Contactez-nous pour plus d\'informations',
  },
  booking: {
    title: 'Réserver Maintenant',
    subtitle: 'Remplissez vos informations et notre équipe professionnelle vous contactera bientôt',
    firstName: 'Prénom',
    lastName: 'Nom',
    email: 'Email',
    phone: 'Téléphone',
    required: '*',
    firstNamePlaceholder: 'Prénom',
    lastNamePlaceholder: 'Nom',
    emailPlaceholder: 'Entrez votre adresse email',
    phonePlaceholder: 'Entrez votre numéro de téléphone',
    submit: 'Soumettre la Réservation',
    submitting: 'Envoi en cours...',
    vipTitle: 'Adhésion VIP à Vie',
    vipPrice: '$200',
    vipDescription: 'Profitez de services exclusifs et d\'offres spéciales à vie',
    selectServices: 'Sélectionner les Services',
    injection: 'Amélioration par Injection',
    injectionDesc: 'Solutions d\'injection mini-invasives',
    injectionPrice: '$40',
    surgery: 'Amélioration Chirurgicale',
    surgeryDesc: 'Solutions chirurgicales professionnelles',
    surgeryPrice: '$80',
    hairConsult: 'Consultation Capillaire',
    hairConsultDesc: 'Consultation professionnelle de santé capillaire',
    hairConsultPrice: '$20',
    paypalPayment: 'Payer avec PayPal',
    cardPayment: 'Payer par Carte',
    processing: 'Traitement...',
    backToHome: 'Retour à l\'Accueil',
    successTitle: 'Réservation Réussie!',
    successMessage: 'Votre réservation est confirmée, notre équipe vous contactera bientôt',
  },
};

const arTranslations = {
  nav: {
    home: 'الرئيسية',
    projects: 'المشاريع',
    cases: 'الحالات',
    faq: 'الأسئلة الشائعة',
    login: 'تسجيل الدخول',
    logout: 'تسجيل الخروج',
    bookNow: 'احجز الآن',
    facialContour: 'نحت الوجه',
    bodySculpting: 'نحت الجسم',
    facialRejuvenation: 'تجديد الوجه',
    hairTransplant: 'زراعة الشعر',
    dental: 'تجميل الأسنان',
  },
  hero: {
    title1: 'فقط ما هو طبيعي وفريد من نوعه،',
    title2: 'يجعلك الرمز الأكثر تميزاً في العالم',
    cta: 'ابدأ الاستكشاف الآن',
  },
  services: {
    beforePlaceholder: '[صورة قبل]',
    afterPlaceholder: '[صورة بعد]',
  },
  advantages: {
    title: 'مزايانا',
    advantage1: 'التركيز على التناغم الشامل للوجه',
    advantage2: 'استشارة مهنية',
    advantage3: 'نهج شامل للملامح',
    advantage4: 'تصور نفسك المستقبلية',
    advantage5: 'خطط جمالية مخصصة',
  },
  ethnicity: {
    title: 'ملامح الوجه حسب العرق',
    subtitle: 'التأكيد على التناغم الشامل للوجه مع حلول مخصصة بناءً على المبادئ الجمالية للأعراق المختلفة',
    black: 'أفريقي',
    asian: 'آسيوي',
    white: 'قوقازي',
    boneFeatures: 'البنية العظمية:',
    softTissue: 'الأنسجة الرخوة:',
    blackBone: 'بروز منتصف الوجه مع جسر أنفي منخفض؛ مسافة مدارية أوسع محتملة؛ فك سفلي متطور مع شفاه سميكة ومقلوبة.',
    blackSoft: 'بشرة أكثر سمكاً، مقاومة للتجاعيد لكنها تحتاج عناية بالندبات؛ فتحات أنف واسعة، أنف مسطح، عمود قصير؛ غالباً جفون مزدوجة بمظهر عميق.',
    asianBone: 'عظام وجنة بارزة، فك زاوي، تطور لطيف لعظم الحاجب وحافة المدار.',
    asianSoft: 'نسبة عالية من الجفون الأحادية أو المزدوجة الداخلية مع طيات ملحمية؛ جسر أنفي أقل، طرف مدور، قاعدة أنفية متراجعة؛ أنسجة رخوة ممتلئة نسبياً.',
    whiteBone: 'عظم حاجب وحافة مدار بارزة، عظام وجنة جانبية، خط فك محدد، ذقن مدببة.',
    whiteSoft: 'بشرة أرق مع دهون أقل، عرضة للتجاعيد وبروز العظام؛ جسر أنفي مرتفع، فتحات أنف ضيقة، شفاه أرق؛ جفون مزدوجة واسعة وعميقة.',
    cta: 'افهم ملامح وجهك وابدأ إجراءات فعالة لتحسين مظهرك',
  },
  plan: {
    title: 'احصل على خطة العلاج الخاصة بك',
    subtitle: 'افهم ملامح وجهك وابدأ إجراءات فعالة لتحسين مظهرك',
    before: 'صورة قبل',
    after: 'صورة بعد',
    beforeLabel: 'قبل',
    afterLabel: 'بعد',
    step1: 'تحليل الوجه من قبل الخبراء',
    step2: 'أفضل نسخة منك',
    step3: 'خطة تحسين مخصصة',
    step4: 'شاهد النتائج الرائعة',
  },
  analysis: {
    title: 'وجهك، حلك الفريد',
    subtitle: 'تحليل الوجه سداسي الأبعاد بناءً على البنية العظمية العرقية والعضلات الديناميكية والاحتياجات النفسية',
    dimension1: '١. الخطوط والبنية العظمية',
    dimension2: '٢. الأنسجة الرخوة والبشرة',
    dimension3: '٣. الملامح الفردية',
    dimension4: '٤. الديناميكية والعضلات',
  },
  vision: {
    title: 'هل تساءلت يوماً كيف يمكن أن يبدو وجهك',
    subtitle: 'تصور مستقبلك',
  },
  realCases: {
    title: 'مقارنات الحالات الحقيقية',
    before: 'قبل',
    after: 'بعد',
    months: 'أشهر',
    case1Title1: 'تحسين ملامح الوجه',
    case1Desc1: 'جراحة نحت الوجه المهنية تخلق خطوط وجه أكثر تحديداً',
    case1Title2: 'جسر أنفي طبيعي',
    case1Desc2: 'تقنيات تجميل الأنف الدقيقة تخلق خطوط أنفية مرتفعة طبيعياً',
    case1Title3: 'خط فك محسّن',
    case1Desc3: 'نحت خط فك ناعم وأنيق يعزز التناغم الشامل للوجه',
    case2Title1: 'ملامح عين مصقولة',
    case2Desc1: 'خلق عيون عميقة وآسرة مع نظرة أكثر تعبيراً',
    case2Title2: 'شد البشرة',
    case2Desc2: 'تحسين ترهل البشرة، استعادة الثبات الشبابي',
    case2Title3: 'تحسين شامل',
    case2Desc3: 'تعديلات تفصيلية تخلق جمال وجه طبيعي أكثر تناغماً',
  },
  caseStudies: {
    title: 'قصص النجاح',
    viewAll: 'عرض جميع الحالات',
  },
  testimonials: {
    title: 'ماذا يقول عملاؤنا',
    mapTitle: 'عملاؤنا حول العالم',
    mapSubtitle: 'رضا العملاء هو سعينا الأبدي',
    readMore: 'اقرأ المزيد',
  },
  journey: {
    title: 'ابدأ رحلة تحولك اليوم',
    step1: 'أجب عن الأسئلة',
    step2: 'حمّل الصور',
    step3: 'احصل على خطة مخصصة',
    step4: 'ابدأ رحلتك',
    cta: 'ابدأ تحولك',
  },
  footer: {
    tagline: 'التجميل الطبي المحترف، لتحقيق نسخة أفضل منك',
    about: 'من نحن',
    contact: 'اتصل بنا',
    privacy: 'سياسة الخصوصية',
    terms: 'شروط الخدمة',
  },
  facialContour: {
    title: 'نحت الوجه',
    subtitle: 'نحت دقيق، خلق ملامح محددة',
    exploreNow: 'ابدأ الاستكشاف الآن',
    servicesTitle: 'خدماتنا',
    servicesSubtitle: 'تقنيات احترافية، حلول مخصصة',
    whyChooseUs: 'لماذا تختارنا',
    realCasesTitle: 'حالات حقيقية',
    realCasesSubtitle: 'شاهد التحولات الجميلة',
  },
  bodySculpting: {
    title: 'نحت الجسم',
    subtitle: 'نحت علمي، منحنيات مثالية',
    exploreNow: 'ابدأ الاستكشاف الآن',
    servicesTitle: 'خدماتنا',
    servicesSubtitle: 'نحت احترافي، ثقة متجددة',
    whyChooseUs: 'لماذا تختارنا',
    realCasesTitle: 'حالات حقيقية',
    realCasesSubtitle: 'شاهد التحولات المثالية',
  },
  facialRejuvenation: {
    title: 'تجديد الوجه',
    subtitle: 'نهج غير جراحي، تجديد سهل',
    exploreNow: 'ابدأ الاستكشاف الآن',
    servicesTitle: 'خدماتنا',
    servicesSubtitle: 'تجديد غير جراحي، جمال طبيعي',
    injection: 'الرفع بالحقن',
    injectionDesc: 'تنعيم التجاعيد الديناميكية',
    diamond: 'رفع الماس 7D',
    diamondDesc: 'استعادة امتلاء الوجه',
    whyChooseUs: 'لماذا تختارنا',
    realCasesTitle: 'حالات حقيقية',
    realCasesSubtitle: 'شاهد التحولات الجميلة',
  },
  hairTransplant: {
    title: 'زراعة الشعر',
    subtitle: 'تقنية احترافية، استعد شعرك الكثيف',
    exploreNow: 'ابدأ الاستكشاف الآن',
    servicesTitle: 'تقنيات الزراعة',
    servicesSubtitle: 'تقنية متقدمة، نتائج طبيعية',
    whyChooseUs: 'لماذا تختارنا',
    realCasesTitle: 'حالات حقيقية',
    realCasesSubtitle: 'شاهد ولادة الشعر من جديد',
  },
  dental: {
    title: 'تجميل الأسنان',
    subtitle: 'جماليات فموية احترافية، ابتسامة واثقة',
    exploreNow: 'ابدأ الاستكشاف الآن',
    servicesTitle: 'خدماتنا',
    servicesSubtitle: 'تقنيات رائعة، ابتسامة مثالية',
    whyChooseUs: 'لماذا تختارنا',
    realCasesTitle: 'حالات حقيقية',
    realCasesSubtitle: 'شاهد الابتسامات المشرقة',
  },
  cases: {
    title: 'قصص النجاح',
    subtitle: 'تحولات حقيقية، شهادة على الجمال',
    filterAll: 'الكل',
    searchPlaceholder: 'بحث عن حالات...',
    loadMore: 'تحميل المزيد',
    noResults: 'لم يتم العثور على حالات',
  },
  faq: {
    title: 'الأسئلة المتكررة',
    subtitle: 'الإجابة على أسئلتك',
    general: 'أسئلة عامة',
    safety: 'متعلق بالسلامة',
    recovery: 'متعلق بالتعافي',
    cost: 'متعلق بالتكلفة',
    q1: 'هل الجراحة التجميلية آمنة؟',
    a1: 'نستخدم معدات ومواد متطورة، يديرها فرق طبية ذات خبرة، مما يضمن السلامة الجراحية.',
    q2: 'كم تستغرق فترة التعافي؟',
    a2: 'يختلف وقت التعافي حسب نوع الجراحة. الإجراءات البسيطة ليس لها تقريباً وقت توقف، الإجراءات الجراحية تتطلب عادة 1-2 أسابيع.',
    q3: 'كم تدوم النتائج؟',
    a3: 'عادة ما تدوم العلاجات القابلة للحقن 6-12 شهراً، يمكن أن يكون للإجراءات الجراحية تأثيرات طويلة الأمد.',
    q4: 'كيف يتم حساب التكاليف؟',
    a4: 'تعتمد التكاليف على الإجراءات المحددة والظروف الفردية. نقدم أسعاراً شفافة بعد الاستشارة.',
    contactUs: 'هل لديك أسئلة أخرى؟',
    contactCTA: 'اتصل بنا للحصول على مزيد من المعلومات',
  },
  booking: {
    title: 'احجز الآن',
    subtitle: 'املأ معلوماتك وسيتصل بك فريقنا المحترف قريباً',
    firstName: 'الاسم الأول',
    lastName: 'اسم العائلة',
    email: 'البريد الإلكتروني',
    phone: 'الهاتف',
    required: '*',
    firstNamePlaceholder: 'الاسم الأول',
    lastNamePlaceholder: 'اسم العائلة',
    emailPlaceholder: 'أدخل عنوان بريدك الإلكتروني',
    phonePlaceholder: 'أدخل رقم هاتفك',
    submit: 'إرسال الحجز',
    submitting: 'جاري الإرسال...',
    vipTitle: 'عضوية VIP مدى الحياة',
    vipPrice: '$200',
    vipDescription: 'استمتع بخدمات حصرية وعروض خاصة مدى الحياة',
    selectServices: 'اختر الخدمات',
    injection: 'التحسين بالحقن',
    injectionDesc: 'حلول حقن طفيفة التوغل',
    injectionPrice: '$40',
    surgery: 'التحسين الجراحي',
    surgeryDesc: 'حلول جراحية احترافية',
    surgeryPrice: '$80',
    hairConsult: 'استشارة الشعر',
    hairConsultDesc: 'استشارة صحة الشعر الاحترافية',
    hairConsultPrice: '$20',
    paypalPayment: 'الدفع بواسطة PayPal',
    cardPayment: 'الدفع بالبطاقة',
    processing: 'جاري المعالجة...',
    backToHome: 'العودة إلى الصفحة الرئيسية',
    successTitle: 'تم الحجز بنجاح!',
    successMessage: 'تم تأكيد حجزك، سيتصل بك فريقنا قريباً',
  },
};

const esTranslations = {
  nav: {
    home: 'Inicio',
    projects: 'Proyectos',
    cases: 'Casos',
    faq: 'Preguntas Frecuentes',
    login: 'Iniciar Sesión',
    logout: 'Cerrar Sesión',
    bookNow: 'Reservar Ahora',
    facialContour: 'Contorno Facial',
    bodySculpting: 'Escultura Corporal',
    facialRejuvenation: 'Rejuvenecimiento Facial',
    hairTransplant: 'Trasplante Capilar',
    dental: 'Estética Dental',
  },
  hero: {
    title1: 'Solo lo que es naturalmente único,',
    title2: 'Te hace el símbolo más distintivo del mundo',
    cta: 'Comienza a Explorar Ahora',
  },
  services: {
    beforePlaceholder: '[Foto Antes]',
    afterPlaceholder: '[Foto Después]',
  },
  advantages: {
    title: 'Nuestras Ventajas',
    advantage1: 'Enfoque en la Armonía Facial General',
    advantage2: 'Consulta Profesional',
    advantage3: 'Enfoque Holístico de Características',
    advantage4: 'Visualiza Tu Yo Futuro',
    advantage5: 'Planes Estéticos Personalizados',
  },
  ethnicity: {
    title: 'Características Faciales por Etnia',
    subtitle: 'Enfatizando la armonía facial general con soluciones personalizadas basadas en principios estéticos para diferentes etnias',
    black: 'Africano',
    asian: 'Asiático',
    white: 'Caucásico',
    boneFeatures: 'Estructura Ósea:',
    softTissue: 'Tejido Blando:',
    blackBone: 'Protrusión del tercio medio con puente nasal bajo; posiblemente mayor distancia orbital; mandíbula desarrollada con labios gruesos y evertidos.',
    blackSoft: 'Piel más gruesa, resistente a arrugas pero requiere atención a la cicatrización; fosas nasales anchas, nariz plana, columela corta; a menudo párpados dobles con apariencia profunda.',
    asianBone: 'Pómulos prominentes, mandíbula angular, desarrollo suave del hueso de la ceja y borde orbital.',
    asianSoft: 'Alta proporción de párpados simples o dobles internos con pliegues epicánticos; puente nasal más bajo, punta redondeada, base nasal retraída; tejido blando relativamente más lleno.',
    whiteBone: 'Hueso de ceja y borde orbital prominentes, pómulos laterales, línea de mandíbula definida, barbilla puntiaguda.',
    whiteSoft: 'Piel más delgada con menos grasa, propensa a arrugas y prominencia ósea; puente nasal alto, fosas nasales estrechas, labios más delgados; párpados dobles anchos y profundos.',
    cta: 'Comprende tus características faciales y comienza acciones efectivas para mejorar tu apariencia',
  },
  plan: {
    title: 'Obtén Tu Plan de Tratamiento',
    subtitle: 'Comprende tus características faciales y comienza acciones efectivas para mejorar tu apariencia',
    before: 'Foto Antes',
    after: 'Foto Después',
    beforeLabel: 'ANTES',
    afterLabel: 'DESPUÉS',
    step1: 'Análisis Facial Experto',
    step2: 'Tu Mejor Versión',
    step3: 'Plan de Mejora Personalizado',
    step4: 'Presencia Resultados Notables',
  },
  analysis: {
    title: 'Tu Rostro, Tu Solución Única',
    subtitle: 'Análisis facial de seis dimensiones basado en estructura ósea étnica, músculos dinámicos y necesidades psicológicas',
    dimension1: '1. Contorno y Estructura Ósea',
    dimension2: '2. Tejido Blando y Piel',
    dimension3: '3. Características Individuales',
    dimension4: '4. Dinámica y Músculos',
  },
  vision: {
    title: 'Alguna Vez Te Preguntaste Cómo Podría Verse Tu Rostro',
    subtitle: 'Visualiza Tu Futuro',
  },
  realCases: {
    title: 'Comparaciones de Casos Reales',
    before: 'Antes',
    after: 'Después',
    months: 'meses',
    case1Title1: 'Contornos Faciales Mejorados',
    case1Desc1: 'La cirugía profesional de contorno facial crea líneas faciales más definidas',
    case1Title2: 'Puente Nasal Natural',
    case1Desc2: 'Técnicas precisas de rinoplastia crean líneas nasales naturalmente elevadas',
    case1Title3: 'Línea de Mandíbula Optimizada',
    case1Desc3: 'Esculpir una línea de mandíbula suave y elegante mejora la armonía facial general',
    case2Title1: 'Contornos Oculares Refinados',
    case2Desc1: 'Crear ojos profundos y cautivadores con mirada más expresiva',
    case2Title2: 'Firmeza de la Piel',
    case2Desc2: 'Mejorar la flacidez de la piel, restaurar la firmeza juvenil',
    case2Title3: 'Mejora General',
    case2Desc3: 'Ajustes detallados creando belleza facial natural más armoniosa',
  },
  caseStudies: {
    title: 'Historias de Éxito',
    viewAll: 'Ver Todos los Casos',
  },
  testimonials: {
    title: 'Lo Que Dicen Nuestros Clientes',
    mapTitle: 'Nuestros Clientes en Todo el Mundo',
    mapSubtitle: 'La satisfacción del cliente es nuestra búsqueda eterna',
    readMore: 'Leer Más',
  },
  journey: {
    title: 'Comienza Tu Viaje de Transformación Hoy',
    step1: 'Responde Preguntas',
    step2: 'Sube Fotos',
    step3: 'Obtén Plan Personalizado',
    step4: 'Comienza Tu Viaje',
    cta: 'Comienza Tu Transformación',
  },
  footer: {
    tagline: 'Estética Médica Profesional, Logrando una Mejor Versión de Ti',
    about: 'Acerca de',
    contact: 'Contacto',
    privacy: 'Política de Privacidad',
    terms: 'Términos de Servicio',
  },
  facialContour: {
    title: 'Contorno Facial',
    subtitle: 'Escultura Precisa, Crear Rasgos Definidos',
    exploreNow: 'Comienza a Explorar Ahora',
    servicesTitle: 'Nuestros Servicios',
    servicesSubtitle: 'Técnicas Profesionales, Soluciones Personalizadas',
    whyChooseUs: 'Por Qué Elegirnos',
    realCasesTitle: 'Casos Reales',
    realCasesSubtitle: 'Presencia Hermosas Transformaciones',
  },
  bodySculpting: {
    title: 'Escultura Corporal',
    subtitle: 'Contorneado Científico, Curvas Perfectas',
    exploreNow: 'Comienza a Explorar Ahora',
    servicesTitle: 'Nuestros Servicios',
    servicesSubtitle: 'Escultura Profesional, Confianza Renovada',
    whyChooseUs: 'Por Qué Elegirnos',
    realCasesTitle: 'Casos Reales',
    realCasesSubtitle: 'Presencia Transformaciones Perfectas',
  },
  facialRejuvenation: {
    title: 'Rejuvenecimiento Facial',
    subtitle: 'Enfoque No Quirúrgico, Rejuvenecimiento Fácil',
    exploreNow: 'Comienza a Explorar Ahora',
    servicesTitle: 'Nuestros Servicios',
    servicesSubtitle: 'Rejuvenecimiento No Invasivo, Belleza Natural',
    injection: 'Levantamiento Inyectable',
    injectionDesc: 'Suavizar Arrugas Dinámicas',
    diamond: 'Levantamiento Diamante 7D',
    diamondDesc: 'Restaurar Plenitud Facial',
    whyChooseUs: 'Por Qué Elegirnos',
    realCasesTitle: 'Casos Reales',
    realCasesSubtitle: 'Presencia Hermosas Transformaciones',
  },
  hairTransplant: {
    title: 'Trasplante Capilar',
    subtitle: 'Tecnología Profesional, Recupera Cabello Grueso',
    exploreNow: 'Comienza a Explorar Ahora',
    servicesTitle: 'Técnicas de Trasplante',
    servicesSubtitle: 'Tecnología Avanzada, Resultados Naturales',
    whyChooseUs: 'Por Qué Elegirnos',
    realCasesTitle: 'Casos Reales',
    realCasesSubtitle: 'Presencia Renacimiento Capilar',
  },
  dental: {
    title: 'Estética Dental',
    subtitle: 'Estética Oral Profesional, Sonrisa Confiada',
    exploreNow: 'Comienza a Explorar Ahora',
    servicesTitle: 'Nuestros Servicios',
    servicesSubtitle: 'Técnicas Exquisitas, Sonrisa Perfecta',
    whyChooseUs: 'Por Qué Elegirnos',
    realCasesTitle: 'Casos Reales',
    realCasesSubtitle: 'Presencia Sonrisas Brillantes',
  },
  cases: {
    title: 'Historias de Éxito',
    subtitle: 'Transformaciones Reales, Presenciando Belleza',
    filterAll: 'Todos',
    searchPlaceholder: 'Buscar casos...',
    loadMore: 'Cargar Más',
    noResults: 'No se encontraron casos',
  },
  faq: {
    title: 'Preguntas Frecuentes',
    subtitle: 'Respondiendo Tus Preguntas',
    general: 'Preguntas Generales',
    safety: 'Relacionado con Seguridad',
    recovery: 'Relacionado con Recuperación',
    cost: 'Relacionado con Costo',
    q1: '¿Es segura la cirugía estética?',
    a1: 'Utilizamos equipos y materiales avanzados, operados por equipos médicos experimentados, garantizando la seguridad quirúrgica.',
    q2: '¿Cuánto dura el período de recuperación?',
    a2: 'El tiempo de recuperación varía según el tipo de cirugía. Los procedimientos mínimamente invasivos casi no tienen tiempo de inactividad, los procedimientos quirúrgicos típicamente requieren 1-2 semanas.',
    q3: '¿Cuánto duran los resultados?',
    a3: 'Los tratamientos inyectables típicamente duran 6-12 meses, los procedimientos quirúrgicos pueden tener efectos a largo plazo.',
    q4: '¿Cómo se calculan los costos?',
    a4: 'Los costos dependen de procedimientos específicos y circunstancias individuales. Proporcionamos precios transparentes después de la consulta.',
    contactUs: '¿Tienes otras preguntas?',
    contactCTA: 'Contáctanos para más información',
  },
  booking: {
    title: 'Reservar Ahora',
    subtitle: 'Complete su información y nuestro equipo profesional se pondrá en contacto pronto',
    firstName: 'Nombre',
    lastName: 'Apellido',
    email: 'Correo Electrónico',
    phone: 'Teléfono',
    required: '*',
    firstNamePlaceholder: 'Nombre',
    lastNamePlaceholder: 'Apellido',
    emailPlaceholder: 'Ingrese su dirección de correo',
    phonePlaceholder: 'Ingrese su número de teléfono',
    submit: 'Enviar Reserva',
    submitting: 'Enviando...',
    vipTitle: 'Membresía VIP de por Vida',
    vipPrice: '$200',
    vipDescription: 'Disfrute de servicios exclusivos y ofertas especiales de por vida',
    selectServices: 'Seleccionar Servicios',
    injection: 'Mejora por Inyección',
    injectionDesc: 'Soluciones de inyección mínimamente invasivas',
    injectionPrice: '$40',
    surgery: 'Mejora Quirúrgica',
    surgeryDesc: 'Soluciones quirúrgicas profesionales',
    surgeryPrice: '$80',
    hairConsult: 'Consulta Capilar',
    hairConsultDesc: 'Consulta profesional de salud capilar',
    hairConsultPrice: '$20',
    paypalPayment: 'Pagar con PayPal',
    cardPayment: 'Pagar con Tarjeta',
    processing: 'Procesando...',
    backToHome: 'Volver al Inicio',
    successTitle: '¡Reserva Exitosa!',
    successMessage: 'Su reserva está confirmada, nuestro equipo se pondrá en contacto pronto',
  },
};
